POST https://ayoadeoyehng1.herokuapp.com/evaluate
Content-Type: application/json

{
    "operation_type": "please multiply 7 by 10",
    "x": 6,
    "y": 10
}

###
POST http://localhost:8000/evaluate
Content-Type: application/json

{
    "operation_type": "please multiply 7 by 10",
    "x": 6,
    "y": 10
}